### ISSUE TITLE
[Meta-Ticket] Foxy improvements

### ISSUE THREAD

**Issue by carlossvg** [ros2-realtime-demo/pendulum#35]
### General Improvements

- [X] Refactor code to reduce complexity
- [X] Refactor code to use ROS parameters
- [X] Refactor code  
- [X] Add topic statistics support https://github.com/ros2-realtime-demo/pendulum/pull/28
- [x] Add support for ROS tracing tools https://github.com/ros2-realtime-demo/pendulum/issues/9
- [x] Improve code to follow real-time programming guidelines https://github.com/ros2-realtime-demo/pendulum/issues/11
- [ ] Analyze memory allocations
- [x] Use bounded message types
    - [x] Create custom message types
    - [x] Create relay node to re-publish joint state msgs for visualization
- [ ] ~~Create launch files for composable/lifecycle nodes~~ 
- [x] Remove pendulum_msgs_v2
- [x] Make ros2_tracing dependency optional
- [ ] Automatically show demo statistics when launching the demo #63

### ADE

- [x] ADE support for Foxy https://github.com/ros2-realtime-demo/pendulum/pull/28
- [x] Add support for lttng and ros tracing https://github.com/ros2-realtime-demo/pendulum/issues/36

### CI

- [ ] Add sanitizers https://github.com/ros2-realtime-demo/pendulum/issues/30
- [ ] Add coverage measurement

### Testing

- [x] Add unit tests
- [x] Add integration tests
- [ ] Add memory allocations checks in tests (WIP)

### Documentation

- [x] Update install instructions
- [x] Add ADE install instructions (something like this https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/installation.html#installation-and-development-install-ade)
- [x] Update demo run instructions https://github.com/ros2-realtime-demo/pendulum/issues/44
- [ ] Update real-time benchmark demo instructions https://github.com/ros2-realtime-demo/pendulum/issues/45
- [x] Update design doc
- [ ] ~~Add instructions to build an RT kernel in a Raspberry PI~~ => https://github.com/ros-realtime/rtwg_documentation
- [ ] ~~Provide instructions/links to cross-compile the workspace in a Raspberry PI~~ => https://github.com/ros-realtime/rtwg_documentation
- [ ] Provide a configured Raspberry PI image 
- [ ] Add codecov badge
- [ ] Define timing requirements in terms of deadline, jitter, tolerable ranges, etc
- [ ] Add instructions explaining how to use ros2 tracing
